### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by talex5** [avsm/ocaml-dockerfile#46]
Should Ubuntu 16.04 be also added to Deprecated? Its EOL is in 3 days

_Originally posted by @kit-ty-kate in https://github.com/ocurrent/docker-base-images/issues/103#issuecomment-827471804_

**Comment by kit-ty-kate** [comment]
I already opened https://github.com/avsm/ocaml-dockerfile/pull/44, sorry i forgot to open a PR in docker-base-images as well. Doing it now.

**Comment by talex5** [comment]
Oops, I missed that!
